---
galaxy_info:
  author: "Neha"
  description: "Simple database role for demo"
  company: ""
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all

dependencies: []

