---
- name: Converge
  hosts: all

  vars:
    nginx_use_ppa: true
    nginx_remove_default_vhost: true
    nginx_vhosts:
      - server_name: "test.dev"
        root: "/var/www/test"

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: geerlingguy.nginx

  post_tasks:
    - name: Restart nginx using systemctl
      ansible.builtin.shell: systemctl restart nginx


  # post_tasks:
  #   - name: Reload nginx service
  #     service:
  #       name: nginx
  #       state: reloaded

  #   - name: Ensure nginx service is enabled
  #     service:
  #       name: nginx
  #       enabled: yes
