---
# SPDX-License-Identifier: MIT-0
# tasks file for roles/webserver
# roles/webserver/tasks/main.yml
- name: Install Nginx using Galaxy role
  import_role:
    name: geerlingguy.nginx

- import_tasks: install.yml
- import_tasks: configure.yml
- import_tasks: facts.yml
- import_tasks: cleanup.yml
