---
# SPDX-License-Identifier: MIT-0
# tasks file for roles/webserver
# roles/webserver/tasks/main.yml
- name: Install Nginx using Galaxy role
  import_role:
    name: geerlingguy.nginx

- import_tasks: install.yml
- import_tasks: configure.yml
- import_tasks: facts.yml
- import_tasks: cleanup.yml

- name: Copy nginx config
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Restart nginx
